"""Account Type

Revision ID: e87f867b01a4
Revises: d0f1b3d46d30
Create Date: 2026-02-22 13:10:05.706641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e87f867b01a4'
down_revision: Union[str, None] = 'd0f1b3d46d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('type', sa.Integer(), nullable=True))
    op.drop_column('accounts', 'holder_category')
    op.drop_column('accounts', 'account_type')
    op.drop_column('accounts', 'account_subtype')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_subtype', sa.VARCHAR(), nullable=True))
    op.add_column('accounts', sa.Column('account_type', sa.VARCHAR(), nullable=True))
    op.add_column('accounts', sa.Column('holder_category', sa.VARCHAR(), nullable=True))
    op.drop_column('accounts', 'type')
    # ### end Alembic commands ###
