"""Auto-Increment ID For TXN

Revision ID: a96d7659a1ea
Revises: 60c44695c948
Create Date: 2026-02-20 23:46:24.575512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96d7659a1ea'
down_revision: Union[str, None] = '60c44695c948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.alter_column('transactions', 'account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.alter_column('transactions', 'account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('transactions', 'transaction_id')
    # ### end Alembic commands ###
